development:
    host: 172.31.212.115
    port: 1812
    timeout: 10
    secret: apache
    dictionary: radius-dictionary

production:
    host: 172.31.212.115
    port: 1812
    timeout: 10
    secret: apache
    dictionary: radius-dictionary
