development:
    host: 10.0.0.100
    port: 1812
    timeout: 10
    secret: rails
    dictionary: radius-dictionary

production:
    host: 10.0.0.100
    port: 1812
    timeout: 10
    secret: rails
    dictionary: radius-dictionary
